### PR TITLE
[TCP/Buffer] Add missing header

### PR DESCRIPTION
**Pull request by Aidyn-A**
The TOT compilation fails with:
```
FAILED: third_party/gloo/gloo/CMakeFiles/gloo.dir/transport/tcp/buffer.cc.o 
...
~/git/pytorch/third_party/gloo/gloo/transport/tcp/buffer.cc: In member function ‘virtual void gloo::transport::tcp::Buffer::send(size_t, size_t, size_t)’:
~/git/pytorch/third_party/gloo/gloo/transport/tcp/buffer.cc:130:53: error: ‘__NR_gettid’ was not declared in this scope
  130 |     std::cout << "[" << getpid() << ": " << syscall(__NR_gettid) << "] ";
```
due to missing `sys/syscall.h` header declaration in `buffer.cc` introduced in commit aeca18386713535f371ab0a969365d50bc505610.

### CODE REVIEW

**Comment by Aidyn-A** [comment]
cc @c-p-i-o

**Review by c-p-i-o — APPROVED** [review]

**Comment by c-p-i-o** [comment]
oops sorry. I really need to go look at fixing the internal codemod here at facebook. Because internally we use a bazel like build, it seems to ignore build variations.

**Comment by c-p-i-o** [comment]
Also, I'm trying to revive the CI via github workflows. 
Feel free to add any automation there - once I land #395, and #396

**Comment by c-p-i-o** [comment]
Small CI has already landed.
However, I discovered that it's hard for someone in Open Source to land changes into the main branch.
Let me figure out how to land changes for you.

**Comment by c-p-i-o** [comment]
Interestingly, the Facebook internal linter doesn't like this change.

Screenshot 2024-12-02 at 2 40 51 PM

**Comment by c-p-i-o** [comment]
Trying with`#include <asm/unistd_64.h>` instead.

**Comment by c-p-i-o** [comment]
Seems like the internal linter is happy is I use:
```
#include <asm/unistd_64.h>
```
Instead of what you have.

Does using the header above resolve the linker error for you @Aidyn-A ?

**Comment by Aidyn-A** [comment]
I think it will no longer be system agnostic once we do `#include <asm/unistd_64.h>`. Calling `syscall(SYS_gettid)` instead of `syscall(__NR_gettid)` should make clang-tidy happy.
